import { readdirSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { join } from 'node:path'
import yaml from 'yaml'

const themesDir = join(process.cwd(), 'src', 'themes')
const outDir = join(process.cwd(), 'src', 'theme')
const outFile = join(outDir, 'themes.generated.ts')

mkdirSync(outDir, { recursive: true })

const files = readdirSync(themesDir).filter((f) => f.endsWith('.yml') || f.endsWith('.yaml'))

const themes: Record<string, any> = {}

for (const file of files) {
  const full = join(themesDir, file)
  const raw = readFileSync(full, 'utf8')
  const parsed = yaml.parse(raw)
  if (!parsed?.id) {
    console.warn(`Skipping theme ${file} – missing id`)
    continue
  }
  themes[parsed.id] = parsed
}

const header = `// AUTO-GENERATED by scripts/generate-themes.mts\n// Do not edit manually.\n\n`
const body = `export const themes = ${JSON.stringify(themes, null, 2)} as const;\n`

writeFileSync(outFile, header + body)

console.log(`Generated ${outFile} with ${Object.keys(themes).length} themes.`)
