// AUTO-GENERATED by scripts/generate-themes.cjs
// Do not edit manually.

export const themes = {
  "green-01": {
    "id": "green-01",
    "name": "Deep Forest Mint",
    "light": {
      "colorScheme": "light",
      "bg": "#F3FBF8",
      "surface": "#FFFFFF",
      "surfaceAlt": "#E0F2EB",
      "border": "#C6DED4",
      "text": "#0F241C",
      "muted": "#6A7F75",
      "primary": "#0F4F3C",
      "primarySoft": "rgba(15, 79, 60, 0.15)",
      "shadowSoft": "0 20px 40px rgba(15, 23, 42, 0.08)"
    },
    "dark": {
      "colorScheme": "dark",
      "bg": "#050D0A",
      "surface": "#0B1713",
      "surfaceAlt": "#11221C",
      "border": "#1D3530",
      "text": "#E5F3EF",
      "muted": "#9EB8AE",
      "primary": "#3A7C63",
      "primarySoft": "rgba(58, 124, 99, 0.25)",
      "shadowSoft": "0 20px 40px rgba(0, 0, 0, 0.7)"
    }
  },
  "green-02": {
    "id": "green-02",
    "name": "Emerald Finance",
    "light": {
      "colorScheme": "light",
      "bg": "#F1FBF7",
      "surface": "#FFFFFF",
      "surfaceAlt": "#E1F3EC",
      "border": "#C5E3D7",
      "text": "#10342A",
      "muted": "#6B8279",
      "primary": "#00896A",
      "primarySoft": "rgba(0, 137, 106, 0.16)",
      "shadowSoft": "0 20px 40px rgba(9, 33, 26, 0.08)"
    },
    "dark": {
      "colorScheme": "dark",
      "bg": "#051410",
      "surface": "#091E18",
      "surfaceAlt": "#0D2A21",
      "border": "#174237",
      "text": "#E4F7F0",
      "muted": "#92B5A8",
      "primary": "#4ABFA2",
      "primarySoft": "rgba(74, 191, 162, 0.28)",
      "shadowSoft": "0 20px 40px rgba(0, 0, 0, 0.75)"
    }
  },
  "green-03": {
    "id": "green-03",
    "name": "Neon Tech Green",
    "light": {
      "colorScheme": "light",
      "bg": "#F4FFF9",
      "surface": "#FFFFFF",
      "surfaceAlt": "#E1FDF0",
      "border": "#C5EEDC",
      "text": "#041812",
      "muted": "#607973",
      "primary": "#00C06A",
      "primarySoft": "rgba(0, 192, 106, 0.18)",
      "shadowSoft": "0 20px 40px rgba(10, 35, 25, 0.08)"
    },
    "dark": {
      "colorScheme": "dark",
      "bg": "#02060A",
      "surface": "#030C10",
      "surfaceAlt": "#051518",
      "border": "#0C2625",
      "text": "#E6FFF4",
      "muted": "#8ED8BF",
      "primary": "#00FF7F",
      "primarySoft": "rgba(0, 255, 127, 0.25)",
      "shadowSoft": "0 20px 40px rgba(0, 0, 0, 0.9)"
    }
  },
  "green-04": {
    "id": "green-04",
    "name": "Alpine Sage",
    "light": {
      "colorScheme": "light",
      "bg": "#F7FBF6",
      "surface": "#FFFFFF",
      "surfaceAlt": "#E7F1E4",
      "border": "#CCD9CA",
      "text": "#253322",
      "muted": "#6B7767",
      "primary": "#5B8A4C",
      "primarySoft": "rgba(91, 138, 76, 0.16)",
      "shadowSoft": "0 20px 40px rgba(15, 23, 42, 0.06)"
    },
    "dark": {
      "colorScheme": "dark",
      "bg": "#070D07",
      "surface": "#0C170E",
      "surfaceAlt": "#132114",
      "border": "#203226",
      "text": "#E6F2E4",
      "muted": "#9CAF9B",
      "primary": "#83AF73",
      "primarySoft": "rgba(131, 175, 115, 0.25)",
      "shadowSoft": "0 20px 40px rgba(0, 0, 0, 0.7)"
    }
  },
  "green-05": {
    "id": "green-05",
    "name": "Dark Botanical",
    "light": {
      "colorScheme": "light",
      "bg": "#F3F7F5",
      "surface": "#FFFFFF",
      "surfaceAlt": "#E0E7E4",
      "border": "#C3CFCA",
      "text": "#111C18",
      "muted": "#65736E",
      "primary": "#184C3A",
      "primarySoft": "rgba(24, 76, 58, 0.18)",
      "shadowSoft": "0 20px 40px rgba(8, 16, 14, 0.08)"
    },
    "dark": {
      "colorScheme": "dark",
      "bg": "#020605",
      "surface": "#050B09",
      "surfaceAlt": "#07110E",
      "border": "#10201A",
      "text": "#DDEAE5",
      "muted": "#8FA29B",
      "primary": "#3B7D63",
      "primarySoft": "rgba(59, 125, 99, 0.28)",
      "shadowSoft": "0 20px 40px rgba(0, 0, 0, 0.85)"
    }
  },
  "green-06": {
    "id": "green-06",
    "name": "Fresh Microgreens",
    "light": {
      "colorScheme": "light",
      "bg": "#F8FFF4",
      "surface": "#FFFFFF",
      "surfaceAlt": "#E9F9DD",
      "border": "#CCE8B7",
      "text": "#243416",
      "muted": "#708361",
      "primary": "#63C132",
      "primarySoft": "rgba(99, 193, 50, 0.2)",
      "shadowSoft": "0 20px 40px rgba(24, 45, 10, 0.06)"
    },
    "dark": {
      "colorScheme": "dark",
      "bg": "#050C04",
      "surface": "#081307",
      "surfaceAlt": "#0C1A09",
      "border": "#173013",
      "text": "#EAF8DF",
      "muted": "#99B48B",
      "primary": "#9AE86D",
      "primarySoft": "rgba(154, 232, 109, 0.25)",
      "shadowSoft": "0 20px 40px rgba(0, 0, 0, 0.85)"
    }
  },
  "green-07": {
    "id": "green-07",
    "name": "Teal SaaS",
    "light": {
      "colorScheme": "light",
      "bg": "#F1FAF9",
      "surface": "#FFFFFF",
      "surfaceAlt": "#E0F2F1",
      "border": "#C4E0DE",
      "text": "#123231",
      "muted": "#6A7D7D",
      "primary": "#00897B",
      "primarySoft": "rgba(0, 137, 123, 0.18)",
      "shadowSoft": "0 20px 40px rgba(18, 50, 49, 0.08)"
    },
    "dark": {
      "colorScheme": "dark",
      "bg": "#021010",
      "surface": "#041616",
      "surfaceAlt": "#072020",
      "border": "#113232",
      "text": "#E3F4F3",
      "muted": "#90B0AE",
      "primary": "#4DB6AC",
      "primarySoft": "rgba(77, 182, 172, 0.28)",
      "shadowSoft": "0 20px 40px rgba(0, 0, 0, 0.8)"
    }
  },
  "green-08": {
    "id": "green-08",
    "name": "Minimal Evergreen",
    "light": {
      "colorScheme": "light",
      "bg": "#F5FAF7",
      "surface": "#FFFFFF",
      "surfaceAlt": "#E2EFE7",
      "border": "#C5D9CC",
      "text": "#132018",
      "muted": "#647568",
      "primary": "#2D6A4F",
      "primarySoft": "rgba(45, 106, 79, 0.18)",
      "shadowSoft": "0 20px 40px rgba(15, 23, 42, 0.06)"
    },
    "dark": {
      "colorScheme": "dark",
      "bg": "#040A07",
      "surface": "#07110C",
      "surfaceAlt": "#0B1912",
      "border": "#12251C",
      "text": "#E9F5ED",
      "muted": "#96AB9E",
      "primary": "#52B788",
      "primarySoft": "rgba(82, 183, 136, 0.3)",
      "shadowSoft": "0 20px 40px rgba(0, 0, 0, 0.8)"
    }
  },
  "green-09": {
    "id": "green-09",
    "name": "Lime Creative",
    "light": {
      "colorScheme": "light",
      "bg": "#F8FFE8",
      "surface": "#FFFFFF",
      "surfaceAlt": "#EBFFC4",
      "border": "#D2F59A",
      "text": "#1A2308",
      "muted": "#6D7456",
      "primary": "#7EDB00",
      "primarySoft": "rgba(126, 219, 0, 0.2)",
      "shadowSoft": "0 20px 40px rgba(22, 30, 4, 0.08)"
    },
    "dark": {
      "colorScheme": "dark",
      "bg": "#050808",
      "surface": "#070B07",
      "surfaceAlt": "#0A110A",
      "border": "#151F10",
      "text": "#F4FFE4",
      "muted": "#A6C28D",
      "primary": "#A5FF00",
      "primarySoft": "rgba(165, 255, 0, 0.28)",
      "shadowSoft": "0 20px 40px rgba(0, 0, 0, 0.9)"
    }
  },
  "green-10": {
    "id": "green-10",
    "name": "Eco Dashboard",
    "light": {
      "colorScheme": "light",
      "bg": "#F2FBF3",
      "surface": "#FFFFFF",
      "surfaceAlt": "#E3F4E6",
      "border": "#C7E3CB",
      "text": "#17321C",
      "muted": "#647A69",
      "primary": "#2E7D32",
      "primarySoft": "rgba(46, 125, 50, 0.18)",
      "shadowSoft": "0 20px 40px rgba(18, 50, 28, 0.06)"
    },
    "dark": {
      "colorScheme": "dark",
      "bg": "#041008",
      "surface": "#07170C",
      "surfaceAlt": "#0B2012",
      "border": "#163522",
      "text": "#E5F6E9",
      "muted": "#95AE9B",
      "primary": "#66BB6A",
      "primarySoft": "rgba(102, 187, 106, 0.28)",
      "shadowSoft": "0 20px 40px rgba(0, 0, 0, 0.8)"
    }
  },
  "green-11": {
    "id": "green-11",
    "name": "Pastel Matcha",
    "light": {
      "colorScheme": "light",
      "bg": "#FDFEF9",
      "surface": "#FFFFFF",
      "surfaceAlt": "#F3F8EE",
      "border": "#D9E5CB",
      "text": "#273122",
      "muted": "#74806F",
      "primary": "#9BCB96",
      "primarySoft": "rgba(155, 203, 150, 0.25)",
      "shadowSoft": "0 20px 40px rgba(25, 35, 20, 0.05)"
    },
    "dark": {
      "colorScheme": "dark",
      "bg": "#070B06",
      "surface": "#0B120A",
      "surfaceAlt": "#111A10",
      "border": "#1F2A1E",
      "text": "#EAF4E6",
      "muted": "#A2B19B",
      "primary": "#CDEBC8",
      "primarySoft": "rgba(205, 235, 200, 0.3)",
      "shadowSoft": "0 20px 40px rgba(0, 0, 0, 0.85)"
    }
  },
  "green-12": {
    "id": "green-12",
    "name": "Urban Mobility",
    "light": {
      "colorScheme": "light",
      "bg": "#F4FFF6",
      "surface": "#FFFFFF",
      "surfaceAlt": "#E6FBEF",
      "border": "#C7EFDA",
      "text": "#0E2217",
      "muted": "#678072",
      "primary": "#00C853",
      "primarySoft": "rgba(0, 200, 83, 0.2)",
      "shadowSoft": "0 20px 40px rgba(7, 40, 18, 0.06)"
    },
    "dark": {
      "colorScheme": "dark",
      "bg": "#031009",
      "surface": "#05170D",
      "surfaceAlt": "#082112",
      "border": "#123824",
      "text": "#E5FBEF",
      "muted": "#92B89F",
      "primary": "#5CF18D",
      "primarySoft": "rgba(92, 241, 141, 0.3)",
      "shadowSoft": "0 20px 40px rgba(0, 0, 0, 0.85)"
    }
  },
  "green-13": {
    "id": "green-13",
    "name": "Money Green",
    "light": {
      "colorScheme": "light",
      "bg": "#F3FFF7",
      "surface": "#FFFFFF",
      "surfaceAlt": "#E2F9EA",
      "border": "#C2ECD3",
      "text": "#102616",
      "muted": "#667C6C",
      "primary": "#00C853",
      "primarySoft": "rgba(0, 200, 83, 0.18)",
      "shadowSoft": "0 20px 40px rgba(16, 38, 22, 0.06)"
    },
    "dark": {
      "colorScheme": "dark",
      "bg": "#041008",
      "surface": "#07170D",
      "surfaceAlt": "#0A2113",
      "border": "#143824",
      "text": "#E9FFE9",
      "muted": "#9EC4A0",
      "primary": "#4ADE80",
      "primarySoft": "rgba(74, 222, 128, 0.3)",
      "shadowSoft": "0 20px 40px rgba(0, 0, 0, 0.85)"
    }
  },
  "green-14": {
    "id": "green-14",
    "name": "Blue-Green Data",
    "light": {
      "colorScheme": "light",
      "bg": "#F2FAFB",
      "surface": "#FFFFFF",
      "surfaceAlt": "#E1F2F4",
      "border": "#C4E0E4",
      "text": "#10272A",
      "muted": "#637880",
      "primary": "#00796B",
      "primarySoft": "rgba(0, 121, 107, 0.2)",
      "shadowSoft": "0 20px 40px rgba(16, 39, 42, 0.06)"
    },
    "dark": {
      "colorScheme": "dark",
      "bg": "#031013",
      "surface": "#05181B",
      "surfaceAlt": "#082328",
      "border": "#12363D",
      "text": "#E4F6F7",
      "muted": "#93AEB4",
      "primary": "#26A69A",
      "primarySoft": "rgba(38, 166, 154, 0.3)",
      "shadowSoft": "0 20px 40px rgba(0, 0, 0, 0.85)"
    }
  },
  "green-15": {
    "id": "green-15",
    "name": "Soft Eco Cream",
    "light": {
      "colorScheme": "light",
      "bg": "#FFFDF7",
      "surface": "#FFFFFF",
      "surfaceAlt": "#FFF6E7",
      "border": "#F0E0C4",
      "text": "#302B20",
      "muted": "#867B6A",
      "primary": "#7CB342",
      "primarySoft": "rgba(124, 179, 66, 0.25)",
      "shadowSoft": "0 20px 40px rgba(63, 51, 27, 0.05)"
    },
    "dark": {
      "colorScheme": "dark",
      "bg": "#17120C",
      "surface": "#1E1810",
      "surfaceAlt": "#262016",
      "border": "#3A301E",
      "text": "#FFF6E7",
      "muted": "#C8B392",
      "primary": "#AED581",
      "primarySoft": "rgba(174, 213, 129, 0.3)",
      "shadowSoft": "0 20px 40px rgba(0, 0, 0, 0.85)"
    }
  },
  "green-16": {
    "id": "green-16",
    "name": "Deep Teal Pro",
    "light": {
      "colorScheme": "light",
      "bg": "#F2F9FA",
      "surface": "#FFFFFF",
      "surfaceAlt": "#E0F1F3",
      "border": "#C1DEE3",
      "text": "#102327",
      "muted": "#60767B",
      "primary": "#005B4F",
      "primarySoft": "rgba(0, 91, 79, 0.22)",
      "shadowSoft": "0 20px 40px rgba(16, 35, 38, 0.06)"
    },
    "dark": {
      "colorScheme": "dark",
      "bg": "#020D0F",
      "surface": "#031518",
      "surfaceAlt": "#052024",
      "border": "#0D353A",
      "text": "#E1F4F6",
      "muted": "#8CA7AC",
      "primary": "#00897B",
      "primarySoft": "rgba(0, 137, 123, 0.3)",
      "shadowSoft": "0 20px 40px rgba(0, 0, 0, 0.9)"
    }
  },
  "green-17": {
    "id": "green-17",
    "name": "Desert Green",
    "light": {
      "colorScheme": "light",
      "bg": "#FFF8F1",
      "surface": "#FFFFFF",
      "surfaceAlt": "#F5E9DE",
      "border": "#E3D0C0",
      "text": "#2F2720",
      "muted": "#8A7768",
      "primary": "#355D57",
      "primarySoft": "rgba(53, 93, 87, 0.2)",
      "shadowSoft": "0 20px 40px rgba(60, 45, 30, 0.06)"
    },
    "dark": {
      "colorScheme": "dark",
      "bg": "#18110C",
      "surface": "#201710",
      "surfaceAlt": "#281F17",
      "border": "#3A3025",
      "text": "#F5E9DE",
      "muted": "#C7AFA0",
      "primary": "#5E8A82",
      "primarySoft": "rgba(94, 138, 130, 0.3)",
      "shadowSoft": "0 20px 40px rgba(0, 0, 0, 0.85)"
    }
  },
  "green-18": {
    "id": "green-18",
    "name": "Ultra Minimal Mint",
    "light": {
      "colorScheme": "light",
      "bg": "#FAFFFA",
      "surface": "#FFFFFF",
      "surfaceAlt": "#EAF7EA",
      "border": "#D0E5D0",
      "text": "#1F2A1F",
      "muted": "#6B776B",
      "primary": "#66BB6A",
      "primarySoft": "rgba(102, 187, 106, 0.2)",
      "shadowSoft": "0 20px 40px rgba(20, 35, 20, 0.05)"
    },
    "dark": {
      "colorScheme": "dark",
      "bg": "#070D07",
      "surface": "#0B130B",
      "surfaceAlt": "#111B11",
      "border": "#1F2D1F",
      "text": "#E8F5E9",
      "muted": "#9FB5A1",
      "primary": "#A5D6A7",
      "primarySoft": "rgba(165, 214, 167, 0.3)",
      "shadowSoft": "0 20px 40px rgba(0, 0, 0, 0.85)"
    }
  },
  "green-19": {
    "id": "green-19",
    "name": "Industrial Mint",
    "light": {
      "colorScheme": "light",
      "bg": "#F4F7F6",
      "surface": "#FFFFFF",
      "surfaceAlt": "#E3EBEA",
      "border": "#CBD6D5",
      "text": "#141C1B",
      "muted": "#6A7574",
      "primary": "#3C6E47",
      "primarySoft": "rgba(60, 110, 71, 0.2)",
      "shadowSoft": "0 20px 40px rgba(15, 23, 30, 0.06)"
    },
    "dark": {
      "colorScheme": "dark",
      "bg": "#070C0B",
      "surface": "#0B1210",
      "surfaceAlt": "#111B19",
      "border": "#1D2A27",
      "text": "#E4EFED",
      "muted": "#94A3A0",
      "primary": "#6FA676",
      "primarySoft": "rgba(111, 166, 118, 0.3)",
      "shadowSoft": "0 20px 40px rgba(0, 0, 0, 0.9)"
    }
  },
  "green-20": {
    "id": "green-20",
    "name": "Noir Terminal Green",
    "light": {
      "colorScheme": "light",
      "bg": "#F7FAFC",
      "surface": "#FFFFFF",
      "surfaceAlt": "#E5EDF2",
      "border": "#CCD7E0",
      "text": "#101622",
      "muted": "#6A7485",
      "primary": "#00C06A",
      "primarySoft": "rgba(0, 192, 106, 0.2)",
      "shadowSoft": "0 20px 40px rgba(16, 22, 32, 0.06)"
    },
    "dark": {
      "colorScheme": "dark",
      "bg": "#020408",
      "surface": "#050810",
      "surfaceAlt": "#070C18",
      "border": "#111C2A",
      "text": "#E6ECF5",
      "muted": "#919AB0",
      "primary": "#00FF7F",
      "primarySoft": "rgba(0, 255, 127, 0.35)",
      "shadowSoft": "0 20px 40px rgba(0, 0, 0, 0.95)"
    }
  }
} as const;
